### ISSUE TITLE
I have problem for setup view with kotlin

### ISSUE THREAD

**Issue by mikkipastel** [MasayukiSuda/ExoPlayerFilter#23]
I try to add video filter with video view at my fragment in my application which add video filter before to save this follow example in README.md with kotlin

```
private fun setUpSimpleExoPlayer() {
        val bandwidthMeter = DefaultBandwidthMeter()
        val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory(bandwidthMeter)
        val trackSelector = DefaultTrackSelector(videoTrackSelectionFactory)

        val defaultBandwidthMeter = DefaultBandwidthMeter()
        val dataSourceFactory = DefaultDataSourceFactory(context, Util.getUserAgent(context, "Video-editor"), defaultBandwidthMeter)
        val extractorsFactory = DefaultExtractorsFactory()
        val videoSource = ExtractorMediaSource(Uri.parse(getString(R.string.sample_media_mp4_portrait)), dataSourceFactory, extractorsFactory, null, null)

        player = ExoPlayerFactory.newSimpleInstance(context, trackSelector)

        player.prepare(videoSource)
        player.playWhenReady = true
    }
```

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <com.daasuu.epf.EPlayerView
        android:id="@+id/layoutMovieWrapper"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</LinearLayout>
```

and have error at this which I cannot to fix this, what should I do about this?

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(android.view.Surface)' on a null object reference
at com.daasuu.epf.EPlayerRenderer.onSurfaceCreated(EPlayerRenderer.java:103)
at com.daasuu.epf.EFrameBufferObjectRenderer.onSurfaceCreated(EFrameBufferObjectRenderer.java:40)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)
```

**Comment by MasayukiSuda** [comment]
Don't write EPlayerView in XML. 
Add EPlayerView when onResume.

See sample.
https://github.com/MasayukiSuda/ExoPlayerFilter/blob/master/sample/src/main/java/com/daasuu/exoplayerfilter/MainActivity.java

**Comment by mikkipastel** [comment]
I change my layout file to this that same with activity_main.xml and have some error

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.editvideo.EditVideoActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class com.daasuu.exoplayerfilter.MovieWrapperView
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3190)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
                                                                    at android.app.ActivityThread.access$1000(ActivityThread.java:211)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6946)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.daasuu.exoplayerfilter.MovieWrapperView
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                    at com.example.editvideo.PreviewLocalVideoFragment.onCreateView(PreviewLocalVideoFragment.kt:30)
                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                                                                    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
                                                                    at android.app.Activity.performStart(Activity.java:6613)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3153)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300) 
                                                                    at android.app.ActivityThread.access$1000(ActivityThread.java:211) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:145) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6946) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.daasuu.exoplayerfilter.MovieWrapperView" on path: DexPathList[[zip file "/data/app/com.example-2/base.apk", zip file "/data/app/com.example-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                	at java.lang.C
```

**Comment by mikkipastel** [comment]
I fount this problem cause is MovieWrapperView then I create this class and not found error
