### ISSUE TITLE
Application cache with Exoplayer 2.7.0

### ISSUE THREAD

**Issue by mikkipastel** [MasayukiSuda/ExoPlayerFilter#25]
Hello,

I update Exoplayer to 2.7.0 but have problem in your library about Listener then I revert Exoplayer version 2.6.1

`03-05 18:42:31.721 14389-14389/com.videoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.videoplayer, PID: 14389
                                                                java.lang.NoSuchMethodError: No virtual method addVideoListener(Lcom/google/android/exoplayer2/SimpleExoPlayer$VideoListener;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/com.videoplayer-2/split_lib_dependencies_apk.apk)
                                                                    at com.daasuu.epf.EPlayerView.setSimpleExoPlayer(EPlayerView.java:46)
                                                                    at com.videoplayer.editvideo.FilterVideoFragment.setUpGlPlayerView(FilterVideoFragment.kt:84)
                                                                    at com.videoplayer.editvideo.FilterVideoFragment.onResume(FilterVideoFragment.kt:97)
                                                                    at android.support.v4.app.Fragment.performResume(Fragment.java:2387)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
                                                                    at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1230)
                                                                    at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1857)
                                                                    at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:2704)
                                                                    at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2220)
                                                                    at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                                                                    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3076)
                                                                    at android.view.View.measure(View.java:18870)
                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2392)
                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1416)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1661)
                                                                	at android.view.ViewRootImpl.doTra`

**Comment by Livekus** [comment]
same , simplexoplayer deprecated

**Comment by MasayukiSuda** [comment]
i fixed.

**Comment by txudeep** [comment]
@MasayukiSuda How did you fixed it ???
