### ISSUE TITLE
Default video access cannot be played after Android 8

### ISSUE THREAD

**Issue by MinosPong** [MasayukiSuda/ExoPlayerFilter#40]
I found the following error log when running in the emulator.
Pixel 2 API 29 - Android 9.+
I think this is due to some restriction introduced after android 8. See
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

```
2019-07-01 16:48:33.175 4984-5723/com.daasuu.exoplayerfilter E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.html5videoplayer.net/videos/toystory.mp4
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: Cleartext HTTP traffic to www.html5videoplayer.net not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
```

**Comment by MinosPong** [comment]
Tried with another mp4 used in ExoPlayer and it is working. Suggest updating the default video.
`https://html5demos.com/assets/dizzy.mp4`

**Comment by MasayukiSuda** [comment]
thx. I fix it. please try again.

**Comment by MinosPong** [comment]
Thanks. @ 7f30dd1
