### ISSUE TITLE
Wrong thread exoplayer crash, loading video from file.

### ISSUE THREAD

**Issue by gonzalocdev** [MasayukiSuda/ExoPlayerFilter#47]
```  exoPlayer = ExoPlayerFactory.newSimpleInstance(this)
        exoPlayer!!.repeatMode=Player.REPEAT_MODE_ALL
        exoPlayer!!.playWhenReady=true
        playerView = EPlayerView(this)
        playerView.setSimpleExoPlayer(exoPlayer)
      playerView.setLayoutParams(RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))
        (findViewById<RelativeLayout>(R.id.player_view)).addView(playerView)
        playerView.onResume()
        playerView.setGlFilter(GlSepiaFilter())
        if(!started)playNext()
    }

-------------------------------------------------------------------------------------------------------------------------------------

 2019-09-27 04:41:44.053 29865-29898/me.xx.xxxx W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1231)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:321)
        at com.daasuu.epf.EPlayerRenderer.onSurfaceCreated(EPlayerRenderer.java:103)
        at com.daasuu.epf.EFrameBufferObjectRenderer.onSurfaceCreated(EFrameBufferObjectRenderer.java:40)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
2019-09-27 04:41:44.055 29865-29898/me.xx.xxxx E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4) ```

-------------------------------------------------------------------------------------------------------------------------------------


ExoPlayer Core Version 2.10.2 & 2.10.4
Android Version: Oreo GO
Tried using layout instead of doing it programmatically but is the same.


------------------------------------------------------------------------------------------------------------------------------------

Tried sample app, and is working, but in my app it continues to crash.

**Comment by gonzalocdev** [comment]
Tried the sample app with and without file, and the same issue is thrown, is this not intended to be used with local files?, ill try to fix it in the meantime.
```
2019-09-27 21:51:10.750 12695-12719/com.daasuu.exoplayerfilter W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/troubleshooting.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1231)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:321)
        at com.daasuu.epf.EPlayerRenderer.onSurfaceCreated(EPlayerRenderer.java:103)
        at com.daasuu.epf.EFrameBufferObjectRenderer.onSurfaceCreated(EFrameBufferObjectRenderer.java:40)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by gonzalocdev** [comment]
Solved, the setSurface was called from an opengl thread, when is called from the main thread, it works as intended.

**Comment by ParthP-7** [comment]
> Solved, the setSurface was called from an opengl thread, when is called from the main thread, it works as intended.

Can you please specify more on how can we call that particular function from main thread? I am struggling on the same point
